/**
 * Service Reliability UI — English / Hindi / Telugu
 * Generated by scripts/gen_reliability_i18n.py — do not hand-edit Telugu/Hindi.
 */

export const RELIABILITY_LANGS = [
  { id: 'en', label: "English" },
  { id: 'hi', label: "\u0939\u093f\u0902\u0926\u0940" },
  { id: 'te', label: "\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41" },
];

export const LANG_STORAGE_KEY = '@superridex/reliability_lang';

const UI = {
  en: {
    title: "Service Reliability",
    bannerOk: "Configured for maximum supported reliability",
    bannerOkSub: "Android/OEM can still stop Accessibility after swipe-kill or battery limits.",
    bannerWarn: "Action may be required",
    bannerWarnSub: "Your device may restrict background operation. Follow the checklist below.",
    status: "Status",
    accessibility: "Accessibility Service",
    enabled: "Enabled",
    disabled: "Disabled",
    master: "Auto-accept master",
    on: "ON",
    off: "OFF",
    battery: "Battery optimization",
    batteryOk: "OK",
    batteryRestricted: "Restricted",
    autostart: "Background / Auto-start",
    autostartVerified: "Verified by you",
    autostartCheck: "Check required",
    oem: "OEM",
    autostartHint: "Android cannot detect OEM Auto-start. If you already allowed it in phone settings, tap below.",
    markVerified: "I've allowed Auto-start \u2014 mark as verified",
    clearVerified: "Clear Auto-start verification",
    actions: "Actions",
    viewOem: "View OEM instructions",
    hideOem: "Hide OEM instructions",
    diagnose: "Diagnose Service",
    openA11y: "Open Accessibility Settings",
    openBattery: "Open Battery Settings",
    openAppInfo: "Open App Info",
    improve: "Improve reliability",
    oemMenuNote: "Menu names change by Android/OS version. Look for Autostart, Battery, and Background activity.",
    diagnoseSection: "Diagnose",
    phase: "Engine phase",
    lastA11y: "Last a11y event",
    lastRide: "Last ride signal",
    lastAccept: "Last Accept found",
    lastClick: "Last click",
    success: "SUCCESS",
    diagnoseHint: "Pull to refresh after a ride attempt. This finds the failure point \u2014 it does not bypass Android limits.",
    language: "Language",
    msAgo: "{n} ms ago",
    secAgo: "{n} sec ago",
    minAgo: "{n} min ago"
  },
  hi: {
    title: "\u0938\u0947\u0935\u093e \u0935\u093f\u0936\u094d\u0935\u0938\u0928\u0940\u092f\u0924\u093e",
    bannerOk: "\u0905\u0927\u093f\u0915\u0924\u092e \u0938\u092e\u0930\u094d\u0925\u093f\u0924 \u0935\u093f\u0936\u094d\u0935\u0938\u0928\u0940\u092f\u0924\u093e \u0915\u0947 \u0932\u093f\u090f \u0938\u0947\u091f",
    bannerOkSub: "\u0938\u094d\u0935\u0948\u092a-\u0915\u093f\u0932 \u092f\u093e \u092c\u0948\u091f\u0930\u0940 \u0938\u0940\u092e\u093e \u0915\u0947 \u092c\u093e\u0926 Android/OEM \u0905\u092d\u0940 \u092d\u0940 Accessibility \u092c\u0902\u0926 \u0915\u0930 \u0938\u0915\u0924\u093e \u0939\u0948\u0964",
    bannerWarn: "\u0915\u093e\u0930\u094d\u0930\u0935\u093e\u0908 \u0915\u0940 \u0906\u0935\u0936\u094d\u092f\u0915\u0924\u093e \u0939\u094b \u0938\u0915\u0924\u0940 \u0939\u0948",
    bannerWarnSub: "\u0906\u092a\u0915\u093e \u092b\u093c\u094b\u0928 \u092c\u0948\u0915\u0917\u094d\u0930\u093e\u0909\u0902\u0921 \u091a\u0932\u093e\u0928\u0947 \u0915\u094b \u0930\u094b\u0915 \u0938\u0915\u0924\u093e \u0939\u0948\u0964 \u0928\u0940\u091a\u0947 \u0926\u0940 \u0917\u0908 \u0938\u0942\u091a\u0940 \u0926\u0947\u0916\u0947\u0902\u0964",
    status: "\u0938\u094d\u0925\u093f\u0924\u093f",
    accessibility: "\u090f\u0915\u094d\u0938\u0947\u0938\u093f\u092c\u093f\u0932\u093f\u091f\u0940 \u0938\u0947\u0935\u093e",
    enabled: "\u091a\u093e\u0932\u0942",
    disabled: "\u092c\u0902\u0926",
    master: "\u0911\u091f\u094b-\u090f\u0915\u094d\u0938\u0947\u092a\u094d\u091f \u092e\u093e\u0938\u094d\u091f\u0930",
    on: "ON",
    off: "OFF",
    battery: "\u092c\u0948\u091f\u0930\u0940 \u0905\u0928\u0941\u0915\u0942\u0932\u0928",
    batteryOk: "\u0920\u0940\u0915",
    batteryRestricted: "\u092a\u094d\u0930\u0924\u093f\u092c\u0902\u0927\u093f\u0924",
    autostart: "\u092c\u0948\u0915\u0917\u094d\u0930\u093e\u0909\u0902\u0921 / \u0911\u091f\u094b-\u0938\u094d\u091f\u093e\u0930\u094d\u091f",
    autostartVerified: "\u0906\u092a\u0928\u0947 \u0938\u0924\u094d\u092f\u093e\u092a\u093f\u0924 \u0915\u093f\u092f\u093e",
    autostartCheck: "\u091c\u093e\u0901\u091a \u0906\u0935\u0936\u094d\u092f\u0915",
    oem: "\u092b\u093c\u094b\u0928 \u092c\u094d\u0930\u093e\u0902\u0921",
    autostartHint: "Android \u0911\u091f\u094b-\u0938\u094d\u091f\u093e\u0930\u094d\u091f \u0916\u0941\u0926 \u0928\u0939\u0940\u0902 \u0926\u0947\u0916 \u0938\u0915\u0924\u093e\u0964 \u0905\u0917\u0930 \u0906\u092a\u0928\u0947 \u0938\u0947\u091f\u093f\u0902\u0917 \u092e\u0947\u0902 \u0905\u0928\u0941\u092e\u0924\u093f \u0926\u0947 \u0926\u0940 \u0939\u0948, \u0928\u0940\u091a\u0947 \u091f\u0948\u092a \u0915\u0930\u0947\u0902\u0964",
    markVerified: "\u092e\u0948\u0902\u0928\u0947 \u0911\u091f\u094b-\u0938\u094d\u091f\u093e\u0930\u094d\u091f \u0905\u0928\u0941\u092e\u0924\u093f \u0926\u0940 \u2014 \u0938\u0924\u094d\u092f\u093e\u092a\u093f\u0924 \u0915\u0930\u0947\u0902",
    clearVerified: "\u0911\u091f\u094b-\u0938\u094d\u091f\u093e\u0930\u094d\u091f \u0938\u0924\u094d\u092f\u093e\u092a\u0928 \u0939\u091f\u093e\u090f\u0901",
    actions: "\u0915\u093e\u0930\u094d\u0930\u0935\u093e\u0908",
    viewOem: "OEM \u0928\u093f\u0930\u094d\u0926\u0947\u0936 \u0926\u0947\u0916\u0947\u0902",
    hideOem: "OEM \u0928\u093f\u0930\u094d\u0926\u0947\u0936 \u091b\u093f\u092a\u093e\u090f\u0901",
    diagnose: "\u0938\u0947\u0935\u093e \u091c\u093e\u0901\u091a\u0947\u0902",
    openA11y: "\u090f\u0915\u094d\u0938\u0947\u0938\u093f\u092c\u093f\u0932\u093f\u091f\u0940 \u0938\u0947\u091f\u093f\u0902\u0917 \u0916\u094b\u0932\u0947\u0902",
    openBattery: "\u092c\u0948\u091f\u0930\u0940 \u0938\u0947\u091f\u093f\u0902\u0917 \u0916\u094b\u0932\u0947\u0902",
    openAppInfo: "\u0910\u092a \u091c\u093e\u0928\u0915\u093e\u0930\u0940 \u0916\u094b\u0932\u0947\u0902",
    improve: "\u0935\u093f\u0936\u094d\u0935\u0938\u0928\u0940\u092f\u0924\u093e \u092c\u0922\u093c\u093e\u090f\u0901",
    oemMenuNote: "\u092e\u0947\u0928\u0942 \u0928\u093e\u092e Android/OS \u0915\u0947 \u0905\u0928\u0941\u0938\u093e\u0930 \u092c\u0926\u0932\u0924\u0947 \u0939\u0948\u0902\u0964 Autostart, Battery, Background \u0926\u0947\u0916\u0947\u0902\u0964",
    diagnoseSection: "\u0928\u093f\u0926\u093e\u0928",
    phase: "\u0907\u0902\u091c\u0928 \u091a\u0930\u0923",
    lastA11y: "\u0905\u0902\u0924\u093f\u092e a11y \u0907\u0935\u0947\u0902\u091f",
    lastRide: "\u0905\u0902\u0924\u093f\u092e \u0930\u093e\u0907\u0921 \u0938\u093f\u0917\u094d\u0928\u0932",
    lastAccept: "\u0905\u0902\u0924\u093f\u092e Accept \u092e\u093f\u0932\u093e",
    lastClick: "\u0905\u0902\u0924\u093f\u092e \u0915\u094d\u0932\u093f\u0915",
    success: "\u0938\u092b\u0932",
    diagnoseHint: "\u0930\u093e\u0907\u0921 \u092a\u094d\u0930\u092f\u093e\u0938 \u0915\u0947 \u092c\u093e\u0926 \u092a\u0941\u0932 \u0915\u0930\u0915\u0947 \u0930\u093f\u092b\u094d\u0930\u0947\u0936 \u0915\u0930\u0947\u0902\u0964 \u092f\u0939 \u0938\u092e\u0938\u094d\u092f\u093e \u092c\u0924\u093e\u0924\u093e \u0939\u0948 \u2014 Android \u0938\u0940\u092e\u093e \u0928\u0939\u0940\u0902 \u0924\u094b\u0921\u093c\u0924\u093e\u0964",
    language: "\u092d\u093e\u0937\u093e",
    msAgo: "{n} \u092e\u093f.\u0938\u0947. \u092a\u0939\u0932\u0947",
    secAgo: "{n} \u0938\u0947\u0915\u0902\u0921 \u092a\u0939\u0932\u0947",
    minAgo: "{n} \u092e\u093f\u0928\u091f \u092a\u0939\u0932\u0947"
  },
  te: {
    title: "\u0c38\u0c47\u0c35 \u0c35\u0c3f\u0c36\u0c4d\u0c35\u0c38\u0c28\u0c40\u0c2f\u0c24",
    bannerOk: "\u0c17\u0c30\u0c3f\u0c37\u0c4d\u0c1f \u0c2e\u0c26\u0c4d\u0c26\u0c24\u0c41 \u0c35\u0c3f\u0c36\u0c4d\u0c35\u0c38\u0c28\u0c40\u0c2f\u0c24\u0c15\u0c41 \u0c38\u0c46\u0c1f\u0c4d \u0c05\u0c2f\u0c3f\u0c02\u0c26\u0c3f",
    bannerOkSub: "\u0c38\u0c4d\u0c35\u0c48\u0c2a\u0c4d-\u0c15\u0c3f\u0c32\u0c4d \u0c32\u0c47\u0c26\u0c3e \u0c2c\u0c4d\u0c2f\u0c3e\u0c1f\u0c30\u0c40 \u0c2a\u0c30\u0c3f\u0c2e\u0c3f\u0c24\u0c41\u0c32 \u0c24\u0c30\u0c4d\u0c35\u0c3e\u0c24 \u0c15\u0c42\u0c21\u0c3e Android/OEM Accessibility \u0c28\u0c3f \u0c06\u0c2a\u0c35\u0c1a\u0c4d\u0c1a\u0c41.",
    bannerWarn: "\u0c1a\u0c30\u0c4d\u0c2f \u0c05\u0c35\u0c38\u0c30\u0c02 \u0c15\u0c3e\u0c35\u0c1a\u0c4d\u0c1a\u0c41",
    bannerWarnSub: "\u0c2e\u0c40 \u0c2b\u0c4b\u0c28\u0c4d \u0c2c\u0c4d\u0c2f\u0c3e\u0c15\u0c4d\u200c\u0c17\u0c4d\u0c30\u0c4c\u0c02\u0c21\u0c4d \u0c2a\u0c28\u0c3f\u0c28\u0c3f \u0c28\u0c3f\u0c30\u0c4b\u0c27\u0c3f\u0c02\u0c1a\u0c35\u0c1a\u0c4d\u0c1a\u0c41. \u0c15\u0c3f\u0c02\u0c26\u0c3f \u0c1c\u0c3e\u0c2c\u0c3f\u0c24\u0c3e \u0c1a\u0c42\u0c21\u0c02\u0c21\u0c3f.",
    status: "\u0c38\u0c4d\u0c25\u0c3f\u0c24\u0c3f",
    accessibility: "\u0c2f\u0c3e\u0c15\u0c4d\u0c38\u0c46\u0c38\u0c3f\u0c2c\u0c3f\u0c32\u0c3f\u0c1f\u0c40 \u0c38\u0c47\u0c35",
    enabled: "\u0c06\u0c28\u0c4d",
    disabled: "\u0c06\u0c2b\u0c4d",
    master: "\u0c06\u0c1f\u0c4b-\u0c05\u0c15\u0c4d\u0c38\u0c46\u0c2a\u0c4d\u0c1f\u0c4d \u0c2e\u0c3e\u0c38\u0c4d\u0c1f\u0c30\u0c4d",
    on: "ON",
    off: "OFF",
    battery: "\u0c2c\u0c4d\u0c2f\u0c3e\u0c1f\u0c30\u0c40 \u0c06\u0c2a\u0c4d\u0c1f\u0c3f\u0c2e\u0c48\u0c1c\u0c47\u0c37\u0c28\u0c4d",
    batteryOk: "\u0c38\u0c30\u0c47",
    batteryRestricted: "\u0c28\u0c3f\u0c2f\u0c02\u0c24\u0c4d\u0c30\u0c3f\u0c02\u0c1a\u0c2c\u0c21\u0c3f\u0c02\u0c26\u0c3f",
    autostart: "\u0c2c\u0c4d\u0c2f\u0c3e\u0c15\u0c4d\u200c\u0c17\u0c4d\u0c30\u0c4c\u0c02\u0c21\u0c4d / \u0c06\u0c1f\u0c4b-\u0c38\u0c4d\u0c1f\u0c3e\u0c30\u0c4d\u0c1f\u0c4d",
    autostartVerified: "\u0c2e\u0c40\u0c30\u0c41 \u0c28\u0c3f\u0c30\u0c4d\u0c27\u0c3e\u0c30\u0c3f\u0c02\u0c1a\u0c3e\u0c30\u0c41",
    autostartCheck: "\u0c24\u0c28\u0c3f\u0c16\u0c40 \u0c05\u0c35\u0c38\u0c30\u0c02",
    oem: "\u0c2b\u0c4b\u0c28\u0c4d \u0c2c\u0c4d\u0c30\u0c3e\u0c02\u0c21\u0c4d",
    autostartHint: "Android \u0c06\u0c1f\u0c4b-\u0c38\u0c4d\u0c1f\u0c3e\u0c30\u0c4d\u0c1f\u0c4d\u200c\u0c28\u0c41 \u0c38\u0c4d\u0c35\u0c2f\u0c02\u0c17\u0c3e \u0c1a\u0c42\u0c21\u0c32\u0c47\u0c26\u0c41. \u0c38\u0c46\u0c1f\u0c4d\u0c1f\u0c3f\u0c02\u0c17\u0c4d\u0c38\u0c4d\u200c\u0c32\u0c4b \u0c05\u0c28\u0c41\u0c2e\u0c24\u0c3f \u0c07\u0c1a\u0c4d\u0c1a\u0c3f \u0c09\u0c02\u0c1f\u0c47 \u0c15\u0c3f\u0c02\u0c26 \u0c1f\u0c4d\u0c2f\u0c3e\u0c2a\u0c4d \u0c1a\u0c47\u0c2f\u0c02\u0c21\u0c3f.",
    markVerified: "\u0c28\u0c47\u0c28\u0c41 \u0c06\u0c1f\u0c4b-\u0c38\u0c4d\u0c1f\u0c3e\u0c30\u0c4d\u0c1f\u0c4d \u0c05\u0c28\u0c41\u0c2e\u0c24\u0c3f\u0c02\u0c1a\u0c3e\u0c28\u0c41 \u2014 \u0c28\u0c3f\u0c30\u0c4d\u0c27\u0c3e\u0c30\u0c3f\u0c02\u0c1a\u0c41",
    clearVerified: "\u0c06\u0c1f\u0c4b-\u0c38\u0c4d\u0c1f\u0c3e\u0c30\u0c4d\u0c1f\u0c4d \u0c28\u0c3f\u0c30\u0c4d\u0c27\u0c3e\u0c30\u0c23 \u0c24\u0c4a\u0c32\u0c17\u0c3f\u0c02\u0c1a\u0c41",
    actions: "\u0c1a\u0c30\u0c4d\u0c2f\u0c32\u0c41",
    viewOem: "OEM \u0c38\u0c42\u0c1a\u0c28\u0c32\u0c41 \u0c1a\u0c42\u0c21\u0c02\u0c21\u0c3f",
    hideOem: "OEM \u0c38\u0c42\u0c1a\u0c28\u0c32\u0c41 \u0c26\u0c3e\u0c1a\u0c02\u0c21\u0c3f",
    diagnose: "\u0c38\u0c47\u0c35\u0c28\u0c41 \u0c2a\u0c30\u0c3f\u0c36\u0c40\u0c32\u0c3f\u0c02\u0c1a\u0c02\u0c21\u0c3f",
    openA11y: "\u0c2f\u0c3e\u0c15\u0c4d\u0c38\u0c46\u0c38\u0c3f\u0c2c\u0c3f\u0c32\u0c3f\u0c1f\u0c40 \u0c38\u0c46\u0c1f\u0c4d\u0c1f\u0c3f\u0c02\u0c17\u0c4d\u0c38\u0c4d \u0c24\u0c46\u0c30\u0c35\u0c02\u0c21\u0c3f",
    openBattery: "\u0c2c\u0c4d\u0c2f\u0c3e\u0c1f\u0c30\u0c40 \u0c38\u0c46\u0c1f\u0c4d\u0c1f\u0c3f\u0c02\u0c17\u0c4d\u0c38\u0c4d \u0c24\u0c46\u0c30\u0c35\u0c02\u0c21\u0c3f",
    openAppInfo: "\u0c2f\u0c3e\u0c2a\u0c4d \u0c38\u0c2e\u0c3e\u0c1a\u0c3e\u0c30\u0c02 \u0c24\u0c46\u0c30\u0c35\u0c02\u0c21\u0c3f",
    improve: "\u0c35\u0c3f\u0c36\u0c4d\u0c35\u0c38\u0c28\u0c40\u0c2f\u0c24 \u0c2a\u0c46\u0c02\u0c1a\u0c02\u0c21\u0c3f",
    oemMenuNote: "\u0c2e\u0c46\u0c28\u0c42 \u0c2a\u0c47\u0c30\u0c4d\u0c32\u0c41 Android/OS \u0c35\u0c46\u0c30\u0c4d\u0c37\u0c28\u0c4d\u200c\u0c24\u0c4b \u0c2e\u0c3e\u0c30\u0c24\u0c3e\u0c2f\u0c3f. Autostart, Battery, Background \u0c1a\u0c42\u0c21\u0c02\u0c21\u0c3f.",
    diagnoseSection: "\u0c28\u0c3f\u0c30\u0c4d\u0c27\u0c3e\u0c30\u0c23",
    phase: "\u0c07\u0c02\u0c1c\u0c3f\u0c28\u0c4d \u0c26\u0c36",
    lastA11y: "\u0c1a\u0c3f\u0c35\u0c30\u0c3f a11y \u0c08\u0c35\u0c46\u0c02\u0c1f\u0c4d",
    lastRide: "\u0c1a\u0c3f\u0c35\u0c30\u0c3f \u0c30\u0c48\u0c21\u0c4d \u0c38\u0c3f\u0c17\u0c4d\u0c28\u0c32\u0c4d",
    lastAccept: "\u0c1a\u0c3f\u0c35\u0c30\u0c3f Accept \u0c26\u0c4a\u0c30\u0c3f\u0c15\u0c3f\u0c02\u0c26\u0c3f",
    lastClick: "\u0c1a\u0c3f\u0c35\u0c30\u0c3f \u0c15\u0c4d\u0c32\u0c3f\u0c15\u0c4d",
    success: "\u0c35\u0c3f\u0c1c\u0c2f\u0c02",
    diagnoseHint: "\u0c30\u0c48\u0c21\u0c4d \u0c2a\u0c4d\u0c30\u0c2f\u0c24\u0c4d\u0c28\u0c02 \u0c24\u0c30\u0c4d\u0c35\u0c3e\u0c24 \u0c2a\u0c41\u0c32\u0c4d \u0c1a\u0c47\u0c38\u0c3f \u0c30\u0c3f\u0c2b\u0c4d\u0c30\u0c46\u0c37\u0c4d \u0c1a\u0c47\u0c2f\u0c02\u0c21\u0c3f. \u0c07\u0c26\u0c3f \u0c38\u0c2e\u0c38\u0c4d\u0c2f \u0c1a\u0c42\u0c2a\u0c3f\u0c38\u0c4d\u0c24\u0c41\u0c02\u0c26\u0c3f \u2014 Android \u0c2a\u0c30\u0c3f\u0c2e\u0c3f\u0c24\u0c41\u0c32\u0c28\u0c41 \u0c26\u0c3e\u0c1f\u0c26\u0c41.",
    language: "\u0c2d\u0c3e\u0c37",
    msAgo: "{n} \u0c2e\u0c3f.\u0c38\u0c46. \u0c15\u0c4d\u0c30\u0c3f\u0c24\u0c02",
    secAgo: "{n} \u0c38\u0c46\u0c15\u0c28\u0c4d\u0c32 \u0c15\u0c4d\u0c30\u0c3f\u0c24\u0c02",
    minAgo: "{n} \u0c28\u0c3f\u0c2e\u0c3f\u0c37\u0c3e\u0c32 \u0c15\u0c4d\u0c30\u0c3f\u0c24\u0c02"
  }
};

const DIAGNOSE = {
  en: {
    A: {
      title: "Accessibility stopped",
      detail: "Accessibility service stopped. Turn it ON again for SUPER RIDEX."
    },
    B: {
      title: "No accessibility events",
      detail: "Service connected, but no accessibility events are being received."
    },
    C: {
      title: "Ride detection quiet",
      detail: "Accessibility events active, ride detection failed (or no ride yet)."
    },
    D: {
      title: "Accept not found",
      detail: "Ride detected, Accept control not found."
    },
    E: {
      title: "Click failed",
      detail: "Accept detected, click action failed."
    },
    F: {
      title: "Next ride missed",
      detail: "Previous acceptance succeeded; subsequent ride detection failed."
    },
    OK: {
      title: "Healthy",
      detail: "Service looks healthy within Android/OEM limits."
    }
  },
  hi: {
    A: {
      title: "\u090f\u0915\u094d\u0938\u0947\u0938\u093f\u092c\u093f\u0932\u093f\u091f\u0940 \u092c\u0902\u0926",
      detail: "\u090f\u0915\u094d\u0938\u0947\u0938\u093f\u092c\u093f\u0932\u093f\u091f\u0940 \u0938\u0947\u0935\u093e \u092c\u0902\u0926 \u0939\u0948\u0964 SUPER RIDEX \u0915\u0947 \u0932\u093f\u090f \u092b\u093f\u0930 \u0938\u0947 ON \u0915\u0930\u0947\u0902\u0964"
    },
    B: {
      title: "\u0915\u094b\u0908 \u0907\u0935\u0947\u0902\u091f \u0928\u0939\u0940\u0902",
      detail: "\u0938\u0947\u0935\u093e \u091c\u0941\u0921\u093c\u0940 \u0939\u0948, \u0932\u0947\u0915\u093f\u0928 \u090f\u0915\u094d\u0938\u0947\u0938\u093f\u092c\u093f\u0932\u093f\u091f\u0940 \u0907\u0935\u0947\u0902\u091f \u0928\u0939\u0940\u0902 \u0906 \u0930\u0939\u0947\u0964"
    },
    C: {
      title: "\u0930\u093e\u0907\u0921 \u0921\u093f\u091f\u0947\u0915\u094d\u0936\u0928 \u0936\u093e\u0902\u0924",
      detail: "\u0907\u0935\u0947\u0902\u091f \u0906 \u0930\u0939\u0947 \u0939\u0948\u0902, \u0930\u093e\u0907\u0921 \u0921\u093f\u091f\u0947\u0915\u094d\u0936\u0928 \u0928\u0939\u0940\u0902 \u0939\u0941\u0908 (\u092f\u093e \u0905\u092d\u0940 \u0930\u093e\u0907\u0921 \u0928\u0939\u0940\u0902)\u0964"
    },
    D: {
      title: "Accept \u0928\u0939\u0940\u0902 \u092e\u093f\u0932\u093e",
      detail: "\u0930\u093e\u0907\u0921 \u092e\u093f\u0932\u0940, Accept \u092c\u091f\u0928 \u0928\u0939\u0940\u0902 \u092e\u093f\u0932\u093e\u0964"
    },
    E: {
      title: "\u0915\u094d\u0932\u093f\u0915 \u0905\u0938\u092b\u0932",
      detail: "Accept \u092e\u093f\u0932\u093e, \u0915\u094d\u0932\u093f\u0915 \u0915\u094d\u0930\u093f\u092f\u093e \u0905\u0938\u092b\u0932\u0964"
    },
    F: {
      title: "\u0905\u0917\u0932\u0940 \u0930\u093e\u0907\u0921 \u091b\u0942\u091f\u0940",
      detail: "\u092a\u093f\u091b\u0932\u093e Accept \u0938\u092b\u0932; \u0905\u0917\u0932\u0940 \u0930\u093e\u0907\u0921 \u0921\u093f\u091f\u0947\u0915\u094d\u0936\u0928 \u0905\u0938\u092b\u0932\u0964"
    },
    OK: {
      title: "\u0938\u094d\u0935\u0938\u094d\u0925",
      detail: "Android/OEM \u0938\u0940\u092e\u093e\u0913\u0902 \u092e\u0947\u0902 \u0938\u0947\u0935\u093e \u0920\u0940\u0915 \u0932\u0917\u0924\u0940 \u0939\u0948\u0964"
    }
  },
  te: {
    A: {
      title: "\u0c2f\u0c3e\u0c15\u0c4d\u0c38\u0c46\u0c38\u0c3f\u0c2c\u0c3f\u0c32\u0c3f\u0c1f\u0c40 \u0c06\u0c2a\u0c3f\u0c35\u0c47\u0c2f\u0c2c\u0c21\u0c3f\u0c02\u0c26\u0c3f",
      detail: "\u0c2f\u0c3e\u0c15\u0c4d\u0c38\u0c46\u0c38\u0c3f\u0c2c\u0c3f\u0c32\u0c3f\u0c1f\u0c40 \u0c38\u0c47\u0c35 \u0c06\u0c2b\u0c4d \u0c09\u0c02\u0c26\u0c3f. SUPER RIDEX \u0c15\u0c4b\u0c38\u0c02 \u0c2e\u0c33\u0c4d\u0c32\u0c40 ON \u0c1a\u0c47\u0c2f\u0c02\u0c21\u0c3f."
    },
    B: {
      title: "\u0c08\u0c35\u0c46\u0c02\u0c1f\u0c4d\u0c32\u0c41 \u0c30\u0c3e\u0c35\u0c21\u0c02 \u0c32\u0c47\u0c26\u0c41",
      detail: "\u0c38\u0c47\u0c35 \u0c15\u0c28\u0c46\u0c15\u0c4d\u0c1f\u0c4d \u0c05\u0c2f\u0c3f\u0c02\u0c26\u0c3f, \u0c15\u0c3e\u0c28\u0c40 \u0c2f\u0c3e\u0c15\u0c4d\u0c38\u0c46\u0c38\u0c3f\u0c2c\u0c3f\u0c32\u0c3f\u0c1f\u0c40 \u0c08\u0c35\u0c46\u0c02\u0c1f\u0c4d\u0c32\u0c41 \u0c30\u0c3e\u0c35\u0c21\u0c02 \u0c32\u0c47\u0c26\u0c41."
    },
    C: {
      title: "\u0c30\u0c48\u0c21\u0c4d \u0c17\u0c41\u0c30\u0c4d\u0c24\u0c3f\u0c02\u0c2a\u0c41 \u0c28\u0c3f\u0c36\u0c4d\u0c36\u0c2c\u0c4d\u0c26\u0c02",
      detail: "\u0c08\u0c35\u0c46\u0c02\u0c1f\u0c4d\u0c32\u0c41 \u0c09\u0c28\u0c4d\u0c28\u0c3e\u0c2f\u0c3f, \u0c30\u0c48\u0c21\u0c4d \u0c17\u0c41\u0c30\u0c4d\u0c24\u0c3f\u0c02\u0c2a\u0c41 \u0c1c\u0c30\u0c17\u0c32\u0c47\u0c26\u0c41 (\u0c32\u0c47\u0c26\u0c3e \u0c07\u0c02\u0c15\u0c3e \u0c30\u0c48\u0c21\u0c4d \u0c30\u0c3e\u0c32\u0c47\u0c26\u0c41)."
    },
    D: {
      title: "Accept \u0c15\u0c28\u0c2c\u0c21\u0c32\u0c47\u0c26\u0c41",
      detail: "\u0c30\u0c48\u0c21\u0c4d \u0c15\u0c28\u0c2c\u0c21\u0c3f\u0c02\u0c26\u0c3f, Accept \u0c2c\u0c1f\u0c28\u0c4d \u0c15\u0c28\u0c2c\u0c21\u0c32\u0c47\u0c26\u0c41."
    },
    E: {
      title: "\u0c15\u0c4d\u0c32\u0c3f\u0c15\u0c4d \u0c35\u0c3f\u0c2b\u0c32\u0c02",
      detail: "Accept \u0c15\u0c28\u0c2c\u0c21\u0c3f\u0c02\u0c26\u0c3f, \u0c15\u0c4d\u0c32\u0c3f\u0c15\u0c4d \u0c1a\u0c30\u0c4d\u0c2f \u0c35\u0c3f\u0c2b\u0c32\u0c2e\u0c48\u0c02\u0c26\u0c3f."
    },
    F: {
      title: "\u0c24\u0c26\u0c41\u0c2a\u0c30\u0c3f \u0c30\u0c48\u0c21\u0c4d \u0c24\u0c2a\u0c4d\u0c2a\u0c3f\u0c02\u0c26\u0c3f",
      detail: "\u0c2e\u0c41\u0c28\u0c41\u0c2a\u0c1f\u0c3f Accept \u0c35\u0c3f\u0c1c\u0c2f\u0c35\u0c02\u0c24\u0c02; \u0c24\u0c26\u0c41\u0c2a\u0c30\u0c3f \u0c30\u0c48\u0c21\u0c4d \u0c17\u0c41\u0c30\u0c4d\u0c24\u0c3f\u0c02\u0c2a\u0c41 \u0c35\u0c3f\u0c2b\u0c32\u0c02."
    },
    OK: {
      title: "\u0c06\u0c30\u0c4b\u0c17\u0c4d\u0c2f\u0c02\u0c17\u0c3e \u0c09\u0c02\u0c26\u0c3f",
      detail: "Android/OEM \u0c2a\u0c30\u0c3f\u0c2e\u0c3f\u0c24\u0c41\u0c32\u0c4d\u0c32\u0c4b \u0c38\u0c47\u0c35 \u0c2c\u0c3e\u0c17\u0c3e\u0c28\u0c47 \u0c09\u0c02\u0c26\u0c3f."
    }
  }
};

const OEM = {
  en: {
    xiaomi: {
      title: "Xiaomi / Redmi / POCO",
      steps: [
        "Open Settings \u2192 Apps \u2192 Permissions \u2192 Autostart (or App launch).",
        "Enable Auto-start / allow background launch for SUPER RIDEX.",
        "Open SUPER RIDEX App info \u2192 Battery \u2192 No restrictions / Allow background.",
        "On HyperOS/MIUI, also check Battery saver \u2192 No restrictions.",
        "Keep Accessibility Service enabled for SUPER RIDEX.",
        "Optional: lock SUPER RIDEX in Recents."
      ]
    },
    oppo: {
      title: "OPPO (ColorOS)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 SUPER RIDEX.",
        "Enable Auto-launch / Auto-start if shown.",
        "Battery \u2192 Allow background activity.",
        "Keep Accessibility Service enabled."
      ]
    },
    vivo: {
      title: "Vivo (Funtouch / OriginOS)",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX.",
        "Battery \u2192 Allow background activity.",
        "Enable Auto-start / High background power if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    realme: {
      title: "realme (realme UI)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 SUPER RIDEX.",
        "Battery usage \u2192 Allow background activity.",
        "Enable Auto-launch / Startup if available.",
        "Keep Accessibility Service enabled."
      ]
    },
    oneplus: {
      title: "OnePlus",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 SUPER RIDEX.",
        "Battery \u2192 Allow background / Unrestricted.",
        "Enable Auto-launch if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    samsung: {
      title: "Samsung (One UI)",
      steps: [
        "Settings \u2192 Battery \u2192 Background usage limits.",
        "Add SUPER RIDEX to Never sleeping apps.",
        "Remove from Sleeping / Deep sleeping apps if listed.",
        "Avoid aggressive Power saving while taking rides.",
        "Keep Accessibility Service enabled."
      ]
    },
    motorola: {
      title: "Motorola",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX.",
        "App battery usage \u2192 Allow background / Unrestricted.",
        "Check Battery optimization is not restricting the app.",
        "Keep Accessibility Service enabled."
      ]
    },
    pixel: {
      title: "Google Pixel / Stock Android",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX \u2192 App battery usage.",
        "Choose Unrestricted for maximum background reliability.",
        "Note: Unrestricted can use more battery.",
        "Keep Accessibility Service enabled."
      ]
    },
    generic: {
      title: "Android (other OEM)",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX.",
        "Allow background activity / disable battery restriction.",
        "Look for Autostart / Auto-launch if available.",
        "Keep Accessibility Service enabled."
      ]
    }
  },
  hi: {
    xiaomi: {
      title: "Xiaomi / Redmi / POCO",
      steps: [
        "Open Settings \u2192 Apps \u2192 Permissions \u2192 Autostart (or App launch).",
        "Enable Auto-start / allow background launch for SUPER RIDEX.",
        "Open SUPER RIDEX App info \u2192 Battery \u2192 No restrictions / Allow background.",
        "On HyperOS/MIUI, also check Battery saver \u2192 No restrictions.",
        "Keep Accessibility Service enabled for SUPER RIDEX.",
        "Optional: lock SUPER RIDEX in Recents."
      ]
    },
    oppo: {
      title: "OPPO (ColorOS)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 SUPER RIDEX.",
        "Enable Auto-launch / Auto-start if shown.",
        "Battery \u2192 Allow background activity.",
        "Keep Accessibility Service enabled."
      ]
    },
    vivo: {
      title: "Vivo (Funtouch / OriginOS)",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX.",
        "Battery \u2192 Allow background activity.",
        "Enable Auto-start / High background power if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    realme: {
      title: "realme (realme UI)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 SUPER RIDEX.",
        "Battery usage \u2192 Allow background activity.",
        "Enable Auto-launch / Startup if available.",
        "Keep Accessibility Service enabled."
      ]
    },
    oneplus: {
      title: "OnePlus",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 SUPER RIDEX.",
        "Battery \u2192 Allow background / Unrestricted.",
        "Enable Auto-launch if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    samsung: {
      title: "Samsung (One UI)",
      steps: [
        "Settings \u2192 Battery \u2192 Background usage limits.",
        "Add SUPER RIDEX to Never sleeping apps.",
        "Remove from Sleeping / Deep sleeping apps if listed.",
        "Avoid aggressive Power saving while taking rides.",
        "Keep Accessibility Service enabled."
      ]
    },
    motorola: {
      title: "Motorola",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX.",
        "App battery usage \u2192 Allow background / Unrestricted.",
        "Check Battery optimization is not restricting the app.",
        "Keep Accessibility Service enabled."
      ]
    },
    pixel: {
      title: "Google Pixel / Stock Android",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX \u2192 App battery usage.",
        "Choose Unrestricted for maximum background reliability.",
        "Note: Unrestricted can use more battery.",
        "Keep Accessibility Service enabled."
      ]
    },
    generic: {
      title: "Android (other OEM)",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX.",
        "Allow background activity / disable battery restriction.",
        "Look for Autostart / Auto-launch if available.",
        "Keep Accessibility Service enabled."
      ]
    }
  },
  te: {
    xiaomi: {
      title: "Xiaomi / Redmi / POCO",
      steps: [
        "Open Settings \u2192 Apps \u2192 Permissions \u2192 Autostart (or App launch).",
        "Enable Auto-start / allow background launch for SUPER RIDEX.",
        "Open SUPER RIDEX App info \u2192 Battery \u2192 No restrictions / Allow background.",
        "On HyperOS/MIUI, also check Battery saver \u2192 No restrictions.",
        "Keep Accessibility Service enabled for SUPER RIDEX.",
        "Optional: lock SUPER RIDEX in Recents."
      ]
    },
    oppo: {
      title: "OPPO (ColorOS)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 SUPER RIDEX.",
        "Enable Auto-launch / Auto-start if shown.",
        "Battery \u2192 Allow background activity.",
        "Keep Accessibility Service enabled."
      ]
    },
    vivo: {
      title: "Vivo (Funtouch / OriginOS)",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX.",
        "Battery \u2192 Allow background activity.",
        "Enable Auto-start / High background power if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    realme: {
      title: "realme (realme UI)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 SUPER RIDEX.",
        "Battery usage \u2192 Allow background activity.",
        "Enable Auto-launch / Startup if available.",
        "Keep Accessibility Service enabled."
      ]
    },
    oneplus: {
      title: "OnePlus",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 SUPER RIDEX.",
        "Battery \u2192 Allow background / Unrestricted.",
        "Enable Auto-launch if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    samsung: {
      title: "Samsung (One UI)",
      steps: [
        "Settings \u2192 Battery \u2192 Background usage limits.",
        "Add SUPER RIDEX to Never sleeping apps.",
        "Remove from Sleeping / Deep sleeping apps if listed.",
        "Avoid aggressive Power saving while taking rides.",
        "Keep Accessibility Service enabled."
      ]
    },
    motorola: {
      title: "Motorola",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX.",
        "App battery usage \u2192 Allow background / Unrestricted.",
        "Check Battery optimization is not restricting the app.",
        "Keep Accessibility Service enabled."
      ]
    },
    pixel: {
      title: "Google Pixel / Stock Android",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX \u2192 App battery usage.",
        "Choose Unrestricted for maximum background reliability.",
        "Note: Unrestricted can use more battery.",
        "Keep Accessibility Service enabled."
      ]
    },
    generic: {
      title: "Android (other OEM)",
      steps: [
        "Settings \u2192 Apps \u2192 SUPER RIDEX.",
        "Allow background activity / disable battery restriction.",
        "Look for Autostart / Auto-launch if available.",
        "Keep Accessibility Service enabled."
      ]
    }
  }
};

export function t(lang, key) {
  const pack = UI[lang] || UI.en;
  return pack[key] ?? UI.en[key] ?? key;
}

export function getDiagnoseCopy(lang, code) {
  const pack = DIAGNOSE[lang] || DIAGNOSE.en;
  return pack[code] || pack.OK || DIAGNOSE.en.OK;
}

export function getOemGuide(lang, oemId) {
  const pack = OEM[lang] || OEM.en;
  return pack[oemId] || pack.generic || OEM.en.generic;
}

export function formatAge(ms, lang = 'en') {
  if (ms == null || ms < 0) return "\u2014";
  const pack = UI[lang] || UI.en;
  if (ms < 1000) return pack.msAgo.replace('{n}', String(ms));
  const s = Math.round(ms / 1000);
  if (s < 60) return pack.secAgo.replace('{n}', String(s));
  const m = Math.round(s / 60);
  return pack.minAgo.replace('{n}', String(m));
}
