/**
 * Service Reliability UI — English / Hindi / Telugu
 * Generated by scripts/gen_reliability_i18n.py — do not hand-edit Telugu/Hindi.
 */

export const RELIABILITY_LANGS = [
  { id: 'en', label: "English" },
  { id: 'hi', label: "\u0939\u093f\u0902\u0926\u0940" },
  { id: 'te', label: "\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41" },
];

export const LANG_STORAGE_KEY = '@superridex/reliability_lang';

const UI = {
  en: {
    title: "Service Reliability",
    bannerOk: "Configured for maximum supported reliability",
    bannerOkSub: "Android/OEM can still stop Accessibility after swipe-kill or battery limits.",
    bannerWarn: "Action may be required",
    bannerWarnSub: "Your device may restrict background operation. Follow the checklist below.",
    status: "Status",
    accessibility: "Accessibility Service",
    enabled: "Enabled",
    disabled: "Disabled",
    master: "Auto-accept master",
    on: "ON",
    off: "OFF",
    battery: "Battery optimization",
    batteryOk: "OK",
    batteryRestricted: "Restricted",
    autostart: "Background / Auto-start",
    autostartVerified: "Verified by you",
    autostartCheck: "Check required",
    oem: "OEM",
    autostartHint: "Android cannot detect OEM Auto-start. If you already allowed it in phone settings, tap below.",
    markVerified: "I've allowed Auto-start \u2014 mark as verified",
    clearVerified: "Clear Auto-start verification",
    actions: "Actions",
    viewOem: "View OEM instructions",
    hideOem: "Hide OEM instructions",
    openA11y: "Open Accessibility Settings",
    openBattery: "Open Battery Settings",
    openAppInfo: "Open App Info",
    improve: "Improve reliability",
    oemMenuNote: "Menu names change by Android/OS version. Look for Autostart, Battery, and Background activity.",
    language: "Language"
  },
  hi: {
    title: "\u0938\u0947\u0935\u093e \u0935\u093f\u0936\u094d\u0935\u0938\u0928\u0940\u092f\u0924\u093e",
    bannerOk: "\u0905\u0927\u093f\u0915\u0924\u092e \u0938\u092e\u0930\u094d\u0925\u093f\u0924 \u0935\u093f\u0936\u094d\u0935\u0938\u0928\u0940\u092f\u0924\u093e \u0915\u0947 \u0932\u093f\u090f \u0938\u0947\u091f",
    bannerOkSub: "\u0938\u094d\u0935\u0948\u092a-\u0915\u093f\u0932 \u092f\u093e \u092c\u0948\u091f\u0930\u0940 \u0938\u0940\u092e\u093e \u0915\u0947 \u092c\u093e\u0926 Android/OEM \u0905\u092d\u0940 \u092d\u0940 Accessibility \u092c\u0902\u0926 \u0915\u0930 \u0938\u0915\u0924\u093e \u0939\u0948\u0964",
    bannerWarn: "\u0915\u093e\u0930\u094d\u0930\u0935\u093e\u0908 \u0915\u0940 \u0906\u0935\u0936\u094d\u092f\u0915\u0924\u093e \u0939\u094b \u0938\u0915\u0924\u0940 \u0939\u0948",
    bannerWarnSub: "\u0906\u092a\u0915\u093e \u092b\u093c\u094b\u0928 \u092c\u0948\u0915\u0917\u094d\u0930\u093e\u0909\u0902\u0921 \u091a\u0932\u093e\u0928\u0947 \u0915\u094b \u0930\u094b\u0915 \u0938\u0915\u0924\u093e \u0939\u0948\u0964 \u0928\u0940\u091a\u0947 \u0926\u0940 \u0917\u0908 \u0938\u0942\u091a\u0940 \u0926\u0947\u0916\u0947\u0902\u0964",
    status: "\u0938\u094d\u0925\u093f\u0924\u093f",
    accessibility: "\u090f\u0915\u094d\u0938\u0947\u0938\u093f\u092c\u093f\u0932\u093f\u091f\u0940 \u0938\u0947\u0935\u093e",
    enabled: "\u091a\u093e\u0932\u0942",
    disabled: "\u092c\u0902\u0926",
    master: "\u0911\u091f\u094b-\u090f\u0915\u094d\u0938\u0947\u092a\u094d\u091f \u092e\u093e\u0938\u094d\u091f\u0930",
    on: "ON",
    off: "OFF",
    battery: "\u092c\u0948\u091f\u0930\u0940 \u0905\u0928\u0941\u0915\u0942\u0932\u0928",
    batteryOk: "\u0920\u0940\u0915",
    batteryRestricted: "\u092a\u094d\u0930\u0924\u093f\u092c\u0902\u0927\u093f\u0924",
    autostart: "\u092c\u0948\u0915\u0917\u094d\u0930\u093e\u0909\u0902\u0921 / \u0911\u091f\u094b-\u0938\u094d\u091f\u093e\u0930\u094d\u091f",
    autostartVerified: "\u0906\u092a\u0928\u0947 \u0938\u0924\u094d\u092f\u093e\u092a\u093f\u0924 \u0915\u093f\u092f\u093e",
    autostartCheck: "\u091c\u093e\u0901\u091a \u0906\u0935\u0936\u094d\u092f\u0915",
    oem: "\u092b\u093c\u094b\u0928 \u092c\u094d\u0930\u093e\u0902\u0921",
    autostartHint: "Android \u0911\u091f\u094b-\u0938\u094d\u091f\u093e\u0930\u094d\u091f \u0916\u0941\u0926 \u0928\u0939\u0940\u0902 \u0926\u0947\u0916 \u0938\u0915\u0924\u093e\u0964 \u0905\u0917\u0930 \u0906\u092a\u0928\u0947 \u0938\u0947\u091f\u093f\u0902\u0917 \u092e\u0947\u0902 \u0905\u0928\u0941\u092e\u0924\u093f \u0926\u0947 \u0926\u0940 \u0939\u0948, \u0928\u0940\u091a\u0947 \u091f\u0948\u092a \u0915\u0930\u0947\u0902\u0964",
    markVerified: "\u092e\u0948\u0902\u0928\u0947 \u0911\u091f\u094b-\u0938\u094d\u091f\u093e\u0930\u094d\u091f \u0905\u0928\u0941\u092e\u0924\u093f \u0926\u0940 \u2014 \u0938\u0924\u094d\u092f\u093e\u092a\u093f\u0924 \u0915\u0930\u0947\u0902",
    clearVerified: "\u0911\u091f\u094b-\u0938\u094d\u091f\u093e\u0930\u094d\u091f \u0938\u0924\u094d\u092f\u093e\u092a\u0928 \u0939\u091f\u093e\u090f\u0901",
    actions: "\u0915\u093e\u0930\u094d\u0930\u0935\u093e\u0908",
    viewOem: "OEM \u0928\u093f\u0930\u094d\u0926\u0947\u0936 \u0926\u0947\u0916\u0947\u0902",
    hideOem: "OEM \u0928\u093f\u0930\u094d\u0926\u0947\u0936 \u091b\u093f\u092a\u093e\u090f\u0901",
    openA11y: "\u090f\u0915\u094d\u0938\u0947\u0938\u093f\u092c\u093f\u0932\u093f\u091f\u0940 \u0938\u0947\u091f\u093f\u0902\u0917 \u0916\u094b\u0932\u0947\u0902",
    openBattery: "\u092c\u0948\u091f\u0930\u0940 \u0938\u0947\u091f\u093f\u0902\u0917 \u0916\u094b\u0932\u0947\u0902",
    openAppInfo: "\u0910\u092a \u091c\u093e\u0928\u0915\u093e\u0930\u0940 \u0916\u094b\u0932\u0947\u0902",
    improve: "\u0935\u093f\u0936\u094d\u0935\u0938\u0928\u0940\u092f\u0924\u093e \u092c\u0922\u093c\u093e\u090f\u0901",
    oemMenuNote: "\u092e\u0947\u0928\u0942 \u0928\u093e\u092e Android/OS \u0915\u0947 \u0905\u0928\u0941\u0938\u093e\u0930 \u092c\u0926\u0932\u0924\u0947 \u0939\u0948\u0902\u0964 Autostart, Battery, Background \u0926\u0947\u0916\u0947\u0902\u0964",
    language: "\u092d\u093e\u0937\u093e"
  },
  te: {
    title: "\u0c38\u0c47\u0c35 \u0c35\u0c3f\u0c36\u0c4d\u0c35\u0c38\u0c28\u0c40\u0c2f\u0c24",
    bannerOk: "\u0c17\u0c30\u0c3f\u0c37\u0c4d\u0c1f \u0c2e\u0c26\u0c4d\u0c26\u0c24\u0c41 \u0c35\u0c3f\u0c36\u0c4d\u0c35\u0c38\u0c28\u0c40\u0c2f\u0c24\u0c15\u0c41 \u0c38\u0c46\u0c1f\u0c4d \u0c05\u0c2f\u0c3f\u0c02\u0c26\u0c3f",
    bannerOkSub: "\u0c38\u0c4d\u0c35\u0c48\u0c2a\u0c4d-\u0c15\u0c3f\u0c32\u0c4d \u0c32\u0c47\u0c26\u0c3e \u0c2c\u0c4d\u0c2f\u0c3e\u0c1f\u0c30\u0c40 \u0c2a\u0c30\u0c3f\u0c2e\u0c3f\u0c24\u0c41\u0c32 \u0c24\u0c30\u0c4d\u0c35\u0c3e\u0c24 \u0c15\u0c42\u0c21\u0c3e Android/OEM Accessibility \u0c28\u0c3f \u0c06\u0c2a\u0c35\u0c1a\u0c4d\u0c1a\u0c41.",
    bannerWarn: "\u0c1a\u0c30\u0c4d\u0c2f \u0c05\u0c35\u0c38\u0c30\u0c02 \u0c15\u0c3e\u0c35\u0c1a\u0c4d\u0c1a\u0c41",
    bannerWarnSub: "\u0c2e\u0c40 \u0c2b\u0c4b\u0c28\u0c4d \u0c2c\u0c4d\u0c2f\u0c3e\u0c15\u0c4d\u200c\u0c17\u0c4d\u0c30\u0c4c\u0c02\u0c21\u0c4d \u0c2a\u0c28\u0c3f\u0c28\u0c3f \u0c28\u0c3f\u0c30\u0c4b\u0c27\u0c3f\u0c02\u0c1a\u0c35\u0c1a\u0c4d\u0c1a\u0c41. \u0c15\u0c3f\u0c02\u0c26\u0c3f \u0c1c\u0c3e\u0c2c\u0c3f\u0c24\u0c3e \u0c1a\u0c42\u0c21\u0c02\u0c21\u0c3f.",
    status: "\u0c38\u0c4d\u0c25\u0c3f\u0c24\u0c3f",
    accessibility: "\u0c2f\u0c3e\u0c15\u0c4d\u0c38\u0c46\u0c38\u0c3f\u0c2c\u0c3f\u0c32\u0c3f\u0c1f\u0c40 \u0c38\u0c47\u0c35",
    enabled: "\u0c06\u0c28\u0c4d",
    disabled: "\u0c06\u0c2b\u0c4d",
    master: "\u0c06\u0c1f\u0c4b-\u0c05\u0c15\u0c4d\u0c38\u0c46\u0c2a\u0c4d\u0c1f\u0c4d \u0c2e\u0c3e\u0c38\u0c4d\u0c1f\u0c30\u0c4d",
    on: "ON",
    off: "OFF",
    battery: "\u0c2c\u0c4d\u0c2f\u0c3e\u0c1f\u0c30\u0c40 \u0c06\u0c2a\u0c4d\u0c1f\u0c3f\u0c2e\u0c48\u0c1c\u0c47\u0c37\u0c28\u0c4d",
    batteryOk: "\u0c38\u0c30\u0c47",
    batteryRestricted: "\u0c28\u0c3f\u0c2f\u0c02\u0c24\u0c4d\u0c30\u0c3f\u0c02\u0c1a\u0c2c\u0c21\u0c3f\u0c02\u0c26\u0c3f",
    autostart: "\u0c2c\u0c4d\u0c2f\u0c3e\u0c15\u0c4d\u200c\u0c17\u0c4d\u0c30\u0c4c\u0c02\u0c21\u0c4d / \u0c06\u0c1f\u0c4b-\u0c38\u0c4d\u0c1f\u0c3e\u0c30\u0c4d\u0c1f\u0c4d",
    autostartVerified: "\u0c2e\u0c40\u0c30\u0c41 \u0c28\u0c3f\u0c30\u0c4d\u0c27\u0c3e\u0c30\u0c3f\u0c02\u0c1a\u0c3e\u0c30\u0c41",
    autostartCheck: "\u0c24\u0c28\u0c3f\u0c16\u0c40 \u0c05\u0c35\u0c38\u0c30\u0c02",
    oem: "\u0c2b\u0c4b\u0c28\u0c4d \u0c2c\u0c4d\u0c30\u0c3e\u0c02\u0c21\u0c4d",
    autostartHint: "Android \u0c06\u0c1f\u0c4b-\u0c38\u0c4d\u0c1f\u0c3e\u0c30\u0c4d\u0c1f\u0c4d\u200c\u0c28\u0c41 \u0c38\u0c4d\u0c35\u0c2f\u0c02\u0c17\u0c3e \u0c1a\u0c42\u0c21\u0c32\u0c47\u0c26\u0c41. \u0c38\u0c46\u0c1f\u0c4d\u0c1f\u0c3f\u0c02\u0c17\u0c4d\u0c38\u0c4d\u200c\u0c32\u0c4b \u0c05\u0c28\u0c41\u0c2e\u0c24\u0c3f \u0c07\u0c1a\u0c4d\u0c1a\u0c3f \u0c09\u0c02\u0c1f\u0c47 \u0c15\u0c3f\u0c02\u0c26 \u0c1f\u0c4d\u0c2f\u0c3e\u0c2a\u0c4d \u0c1a\u0c47\u0c2f\u0c02\u0c21\u0c3f.",
    markVerified: "\u0c28\u0c47\u0c28\u0c41 \u0c06\u0c1f\u0c4b-\u0c38\u0c4d\u0c1f\u0c3e\u0c30\u0c4d\u0c1f\u0c4d \u0c05\u0c28\u0c41\u0c2e\u0c24\u0c3f\u0c02\u0c1a\u0c3e\u0c28\u0c41 \u2014 \u0c28\u0c3f\u0c30\u0c4d\u0c27\u0c3e\u0c30\u0c3f\u0c02\u0c1a\u0c41",
    clearVerified: "\u0c06\u0c1f\u0c4b-\u0c38\u0c4d\u0c1f\u0c3e\u0c30\u0c4d\u0c1f\u0c4d \u0c28\u0c3f\u0c30\u0c4d\u0c27\u0c3e\u0c30\u0c23 \u0c24\u0c4a\u0c32\u0c17\u0c3f\u0c02\u0c1a\u0c41",
    actions: "\u0c1a\u0c30\u0c4d\u0c2f\u0c32\u0c41",
    viewOem: "OEM \u0c38\u0c42\u0c1a\u0c28\u0c32\u0c41 \u0c1a\u0c42\u0c21\u0c02\u0c21\u0c3f",
    hideOem: "OEM \u0c38\u0c42\u0c1a\u0c28\u0c32\u0c41 \u0c26\u0c3e\u0c1a\u0c02\u0c21\u0c3f",
    openA11y: "\u0c2f\u0c3e\u0c15\u0c4d\u0c38\u0c46\u0c38\u0c3f\u0c2c\u0c3f\u0c32\u0c3f\u0c1f\u0c40 \u0c38\u0c46\u0c1f\u0c4d\u0c1f\u0c3f\u0c02\u0c17\u0c4d\u0c38\u0c4d \u0c24\u0c46\u0c30\u0c35\u0c02\u0c21\u0c3f",
    openBattery: "\u0c2c\u0c4d\u0c2f\u0c3e\u0c1f\u0c30\u0c40 \u0c38\u0c46\u0c1f\u0c4d\u0c1f\u0c3f\u0c02\u0c17\u0c4d\u0c38\u0c4d \u0c24\u0c46\u0c30\u0c35\u0c02\u0c21\u0c3f",
    openAppInfo: "\u0c2f\u0c3e\u0c2a\u0c4d \u0c38\u0c2e\u0c3e\u0c1a\u0c3e\u0c30\u0c02 \u0c24\u0c46\u0c30\u0c35\u0c02\u0c21\u0c3f",
    improve: "\u0c35\u0c3f\u0c36\u0c4d\u0c35\u0c38\u0c28\u0c40\u0c2f\u0c24 \u0c2a\u0c46\u0c02\u0c1a\u0c02\u0c21\u0c3f",
    oemMenuNote: "\u0c2e\u0c46\u0c28\u0c42 \u0c2a\u0c47\u0c30\u0c4d\u0c32\u0c41 Android/OS \u0c35\u0c46\u0c30\u0c4d\u0c37\u0c28\u0c4d\u200c\u0c24\u0c4b \u0c2e\u0c3e\u0c30\u0c24\u0c3e\u0c2f\u0c3f. Autostart, Battery, Background \u0c1a\u0c42\u0c21\u0c02\u0c21\u0c3f.",
    language: "\u0c2d\u0c3e\u0c37"
  }
};

const OEM = {
  en: {
    xiaomi: {
      title: "Xiaomi / Redmi / POCO",
      steps: [
        "Open Settings \u2192 Apps \u2192 Permissions \u2192 Autostart (or App launch).",
        "Enable Auto-start / allow background launch for AG rider.",
        "Open AG rider App info \u2192 Battery \u2192 No restrictions / Allow background.",
        "On HyperOS/MIUI, also check Battery saver \u2192 No restrictions.",
        "Keep Accessibility Service enabled for AG rider.",
        "Optional: lock AG rider in Recents."
      ]
    },
    oppo: {
      title: "OPPO (ColorOS)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 AG rider.",
        "Enable Auto-launch / Auto-start if shown.",
        "Battery \u2192 Allow background activity.",
        "Keep Accessibility Service enabled."
      ]
    },
    vivo: {
      title: "Vivo (Funtouch / OriginOS)",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider.",
        "Battery \u2192 Allow background activity.",
        "Enable Auto-start / High background power if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    realme: {
      title: "realme (realme UI)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 AG rider.",
        "Battery usage \u2192 Allow background activity.",
        "Enable Auto-launch / Startup if available.",
        "Keep Accessibility Service enabled."
      ]
    },
    oneplus: {
      title: "OnePlus",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 AG rider.",
        "Battery \u2192 Allow background / Unrestricted.",
        "Enable Auto-launch if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    samsung: {
      title: "Samsung (One UI)",
      steps: [
        "Settings \u2192 Battery \u2192 Background usage limits.",
        "Add AG rider to Never sleeping apps.",
        "Remove from Sleeping / Deep sleeping apps if listed.",
        "Avoid aggressive Power saving while taking rides.",
        "Keep Accessibility Service enabled."
      ]
    },
    motorola: {
      title: "Motorola",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider.",
        "App battery usage \u2192 Allow background / Unrestricted.",
        "Check Battery optimization is not restricting the app.",
        "Keep Accessibility Service enabled."
      ]
    },
    pixel: {
      title: "Google Pixel / Stock Android",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider \u2192 App battery usage.",
        "Choose Unrestricted for maximum background reliability.",
        "Note: Unrestricted can use more battery.",
        "Keep Accessibility Service enabled."
      ]
    },
    generic: {
      title: "Android (other OEM)",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider.",
        "Allow background activity / disable battery restriction.",
        "Look for Autostart / Auto-launch if available.",
        "Keep Accessibility Service enabled."
      ]
    }
  },
  hi: {
    xiaomi: {
      title: "Xiaomi / Redmi / POCO",
      steps: [
        "Open Settings \u2192 Apps \u2192 Permissions \u2192 Autostart (or App launch).",
        "Enable Auto-start / allow background launch for AG rider.",
        "Open AG rider App info \u2192 Battery \u2192 No restrictions / Allow background.",
        "On HyperOS/MIUI, also check Battery saver \u2192 No restrictions.",
        "Keep Accessibility Service enabled for AG rider.",
        "Optional: lock AG rider in Recents."
      ]
    },
    oppo: {
      title: "OPPO (ColorOS)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 AG rider.",
        "Enable Auto-launch / Auto-start if shown.",
        "Battery \u2192 Allow background activity.",
        "Keep Accessibility Service enabled."
      ]
    },
    vivo: {
      title: "Vivo (Funtouch / OriginOS)",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider.",
        "Battery \u2192 Allow background activity.",
        "Enable Auto-start / High background power if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    realme: {
      title: "realme (realme UI)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 AG rider.",
        "Battery usage \u2192 Allow background activity.",
        "Enable Auto-launch / Startup if available.",
        "Keep Accessibility Service enabled."
      ]
    },
    oneplus: {
      title: "OnePlus",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 AG rider.",
        "Battery \u2192 Allow background / Unrestricted.",
        "Enable Auto-launch if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    samsung: {
      title: "Samsung (One UI)",
      steps: [
        "Settings \u2192 Battery \u2192 Background usage limits.",
        "Add AG rider to Never sleeping apps.",
        "Remove from Sleeping / Deep sleeping apps if listed.",
        "Avoid aggressive Power saving while taking rides.",
        "Keep Accessibility Service enabled."
      ]
    },
    motorola: {
      title: "Motorola",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider.",
        "App battery usage \u2192 Allow background / Unrestricted.",
        "Check Battery optimization is not restricting the app.",
        "Keep Accessibility Service enabled."
      ]
    },
    pixel: {
      title: "Google Pixel / Stock Android",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider \u2192 App battery usage.",
        "Choose Unrestricted for maximum background reliability.",
        "Note: Unrestricted can use more battery.",
        "Keep Accessibility Service enabled."
      ]
    },
    generic: {
      title: "Android (other OEM)",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider.",
        "Allow background activity / disable battery restriction.",
        "Look for Autostart / Auto-launch if available.",
        "Keep Accessibility Service enabled."
      ]
    }
  },
  te: {
    xiaomi: {
      title: "Xiaomi / Redmi / POCO",
      steps: [
        "Open Settings \u2192 Apps \u2192 Permissions \u2192 Autostart (or App launch).",
        "Enable Auto-start / allow background launch for AG rider.",
        "Open AG rider App info \u2192 Battery \u2192 No restrictions / Allow background.",
        "On HyperOS/MIUI, also check Battery saver \u2192 No restrictions.",
        "Keep Accessibility Service enabled for AG rider.",
        "Optional: lock AG rider in Recents."
      ]
    },
    oppo: {
      title: "OPPO (ColorOS)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 AG rider.",
        "Enable Auto-launch / Auto-start if shown.",
        "Battery \u2192 Allow background activity.",
        "Keep Accessibility Service enabled."
      ]
    },
    vivo: {
      title: "Vivo (Funtouch / OriginOS)",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider.",
        "Battery \u2192 Allow background activity.",
        "Enable Auto-start / High background power if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    realme: {
      title: "realme (realme UI)",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 AG rider.",
        "Battery usage \u2192 Allow background activity.",
        "Enable Auto-launch / Startup if available.",
        "Keep Accessibility Service enabled."
      ]
    },
    oneplus: {
      title: "OnePlus",
      steps: [
        "Settings \u2192 Apps \u2192 App management \u2192 AG rider.",
        "Battery \u2192 Allow background / Unrestricted.",
        "Enable Auto-launch if shown.",
        "Keep Accessibility Service enabled."
      ]
    },
    samsung: {
      title: "Samsung (One UI)",
      steps: [
        "Settings \u2192 Battery \u2192 Background usage limits.",
        "Add AG rider to Never sleeping apps.",
        "Remove from Sleeping / Deep sleeping apps if listed.",
        "Avoid aggressive Power saving while taking rides.",
        "Keep Accessibility Service enabled."
      ]
    },
    motorola: {
      title: "Motorola",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider.",
        "App battery usage \u2192 Allow background / Unrestricted.",
        "Check Battery optimization is not restricting the app.",
        "Keep Accessibility Service enabled."
      ]
    },
    pixel: {
      title: "Google Pixel / Stock Android",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider \u2192 App battery usage.",
        "Choose Unrestricted for maximum background reliability.",
        "Note: Unrestricted can use more battery.",
        "Keep Accessibility Service enabled."
      ]
    },
    generic: {
      title: "Android (other OEM)",
      steps: [
        "Settings \u2192 Apps \u2192 AG rider.",
        "Allow background activity / disable battery restriction.",
        "Look for Autostart / Auto-launch if available.",
        "Keep Accessibility Service enabled."
      ]
    }
  }
};

export function t(lang, key) {
  const pack = UI[lang] || UI.en;
  return pack[key] ?? UI.en[key] ?? key;
}


export function getOemGuide(lang, oemId) {
  const pack = OEM[lang] || OEM.en;
  return pack[oemId] || pack.generic || OEM.en.generic;
}
